#!/usr/bin/env bun

/**
 * YouTube Transcript Downloader CLI
 *
 * A command-line tool for downloading YouTube video transcripts.
 * Supports multiple output formats (txt, srt, json) and language selection.
 *
 * @module
 */

import { parseArgs, showHelp, showVersion } from "./cli.ts";
import { formatTranscript, getExtension } from "./formatter.ts";
import {
	extractVideoId,
	getTranscript,
	listAvailableTracks,
} from "./transcript.ts";
import type { CliOptions } from "./types.ts";

/**
 * Displays an error message and usage information, then exits.
 *
 * @param message - The error message to display
 */
function exitWithError(message: string): never {
	console.error(`Error: ${message}`);
	console.error("Usage: youtube-transcript-downloader <URL> [options]");
	console.error("See --help for details");
	process.exit(1);
}

/**
 * Lists available caption tracks for a video.
 *
 * @param videoId - The YouTube video ID
 */
async function handleListLanguages(videoId: string): Promise<void> {
	console.log(`Video ID: ${videoId}`);
	console.log("Available captions:");

	const tracks = await listAvailableTracks(videoId);

	if (tracks.length === 0) {
		console.log("  No captions available for this video");
		return;
	}

	for (const track of tracks) {
		const autoLabel = track.isAutoGenerated ? " (auto-generated)" : "";
		console.log(`  ${track.languageCode}: ${track.name}${autoLabel}`);
	}
}

/**
 * Downloads and saves the transcript for a video.
 *
 * @param videoId - The YouTube video ID
 * @param options - CLI options
 */
async function handleDownloadTranscript(
	videoId: string,
	options: CliOptions,
): Promise<void> {
	console.log(`Video ID: ${videoId}`);
	console.log("Fetching transcript...");

	const lines = await getTranscript(videoId, options.lang);
	const content = formatTranscript(lines, options.format, options.timestamps);

	const outputFile =
		options.output ?? `${videoId}.${getExtension(options.format)}`;

	await Bun.write(outputFile, content);

	console.log(`Saved: ${outputFile}`);
	console.log(`Downloaded ${lines.length} lines`);
}

/**
 * Main entry point for the CLI application.
 */
async function main(): Promise<void> {
	const args = process.argv.slice(2);

	let options: CliOptions;
	try {
		options = parseArgs(args);
	} catch (error) {
		if (error instanceof Error) {
			exitWithError(error.message);
		}
		exitWithError("Unknown error occurred");
	}

	if (options.help) {
		showHelp();
		return;
	}

	if (options.version) {
		showVersion();
		return;
	}

	if (!options.url) {
		exitWithError("Please provide a YouTube video URL");
	}

	const videoId = extractVideoId(options.url);
	if (!videoId) {
		exitWithError("Invalid YouTube URL or video ID");
	}

	try {
		if (options.listLangs) {
			await handleListLanguages(videoId);
		} else {
			await handleDownloadTranscript(videoId, options);
		}
	} catch (error) {
		if (error instanceof Error) {
			exitWithError(error.message);
		}
		exitWithError("An unexpected error occurred");
	}
}

main();
