import { describe, expect, test } from "bun:test";
import { extractCaptionTracks, extractVideoId } from "./transcript.ts";

describe("extractVideoId", () => {
	test("extracts video ID from standard YouTube URL", () => {
		const url = "https://www.youtube.com/watch?v=dQw4w9WgXcQ";
		expect(extractVideoId(url)).toBe("dQw4w9WgXcQ");
	});

	test("extracts video ID from short YouTube URL", () => {
		const url = "https://youtu.be/dQw4w9WgXcQ";
		expect(extractVideoId(url)).toBe("dQw4w9WgXcQ");
	});

	test("extracts video ID from embed URL", () => {
		const url = "https://www.youtube.com/embed/dQw4w9WgXcQ";
		expect(extractVideoId(url)).toBe("dQw4w9WgXcQ");
	});

	test("extracts video ID from /v/ URL", () => {
		const url = "https://www.youtube.com/v/dQw4w9WgXcQ";
		expect(extractVideoId(url)).toBe("dQw4w9WgXcQ");
	});

	test("accepts raw video ID", () => {
		const videoId = "dQw4w9WgXcQ";
		expect(extractVideoId(videoId)).toBe("dQw4w9WgXcQ");
	});

	test("handles URL with additional parameters", () => {
		const url = "https://www.youtube.com/watch?v=dQw4w9WgXcQ&t=120";
		expect(extractVideoId(url)).toBe("dQw4w9WgXcQ");
	});

	test("returns null for invalid URL", () => {
		const url = "https://example.com/video";
		expect(extractVideoId(url)).toBeNull();
	});

	test("returns null for empty string", () => {
		expect(extractVideoId("")).toBeNull();
	});

	test("returns null for malformed video ID", () => {
		expect(extractVideoId("abc")).toBeNull();
		expect(extractVideoId("dQw4w9WgXcQextra")).toBeNull();
	});

	test("handles video ID with special characters", () => {
		const videoId = "abc-_123ABC";
		expect(extractVideoId(videoId)).toBe("abc-_123ABC");
	});
});

describe("extractCaptionTracks", () => {
	test("extracts caption tracks from player response", () => {
		const playerResponse = {
			captions: {
				playerCaptionsTracklistRenderer: {
					captionTracks: [
						{
							baseUrl: "https://example.com/caption1",
							languageCode: "en",
							name: { simpleText: "English" },
							kind: "asr",
						},
						{
							baseUrl: "https://example.com/caption2",
							languageCode: "ja",
							name: { simpleText: "Japanese" },
						},
					],
				},
			},
		};

		const tracks = extractCaptionTracks(playerResponse);

		expect(tracks).toHaveLength(2);
		expect(tracks[0]).toEqual({
			baseUrl: "https://example.com/caption1",
			languageCode: "en",
			name: "English",
			isAutoGenerated: true,
		});
		expect(tracks[1]).toEqual({
			baseUrl: "https://example.com/caption2",
			languageCode: "ja",
			name: "Japanese",
			isAutoGenerated: false,
		});
	});

	test("returns empty array when no captions available", () => {
		const playerResponse = {};
		expect(extractCaptionTracks(playerResponse)).toEqual([]);
	});

	test("returns empty array when captionTracks is missing", () => {
		const playerResponse = {
			captions: {
				playerCaptionsTracklistRenderer: {},
			},
		};
		expect(extractCaptionTracks(playerResponse)).toEqual([]);
	});

	test("uses languageCode as fallback for name", () => {
		const playerResponse = {
			captions: {
				playerCaptionsTracklistRenderer: {
					captionTracks: [
						{
							baseUrl: "https://example.com/caption",
							languageCode: "ko",
						},
					],
				},
			},
		};

		const tracks = extractCaptionTracks(playerResponse);
		expect(tracks[0]?.name).toBe("ko");
	});
});
