/**
 * Represents a single line of transcript data.
 */
export interface TranscriptLine {
	/** The text content of the transcript line */
	readonly text: string;
	/** Start time in seconds */
	readonly start: number;
	/** Duration in seconds */
	readonly duration: number;
}

/**
 * Represents an available caption track for a video.
 */
export interface CaptionTrack {
	/** URL to fetch the caption data */
	readonly baseUrl: string;
	/** Language code (e.g., "en", "ja") */
	readonly languageCode: string;
	/** Human-readable language name */
	readonly name: string;
	/** Whether this track was auto-generated */
	readonly isAutoGenerated: boolean;
}

/**
 * Supported output formats for transcript export.
 */
export type OutputFormat = "txt" | "srt" | "json";

/**
 * Command-line interface options.
 */
export interface CliOptions {
	/** YouTube video URL or video ID */
	url: string;
	/** Output filename */
	output?: string;
	/** Preferred language code */
	lang?: string;
	/** Whether to list available languages */
	listLangs: boolean;
	/** Output format */
	format: OutputFormat;
	/** Whether to include timestamps (for txt format) */
	timestamps: boolean;
	/** Whether to show help message */
	help: boolean;
	/** Whether to show version */
	version: boolean;
}

/**
 * Read-only version of CliOptions for use after parsing.
 */
export type ReadonlyCliOptions = Readonly<CliOptions>;
